<Marker>:
	BoxLayout:
		orientation: 'vertical'
		BoxLayout:
			orientation: 'horizontal'	
			Button:
				text: "<<"
				size_hint: 0.15, 1
			Button:
				text: "<<"
				size_hint: 0.15, 1
			Slider:
				id: slider
				min:0
				max: 100
				step: 1
				orientation: 'horizontal'
			Button:
				text: ">"
				size_hint_x: 0.15
			Button:
				text: ">>"
				size_hint_x: 0.15
		FloatLayout:
			text: "NIce"
		Button:
			text: "PlaceHolder"
		Button:
			text: "Placeholder"
